### ISSUE TITLE
Fixes list 😭 

### ISSUE THREAD

**Issue by VCAngel** [montesp/UICmv#21]
## TODO list
- [X] Restaurar color de agujeros entre pestañas
- [X] Colorear fronteras en *Mathematics*: Conditions PDE
- [ ] Ordenar pestañas:
  - [ ] *Heat transfer*: Geometry, Materials, Conditions, Mesh, Library
  - [ ] *Mathematics*: Geometry, Conditions PDE, Coefficient from PDE, Mesh
- [ ] "Ir por pasos" en Model Wizard y demás. Habilitar inputs/botones/etc. hasta que el usuario presione apply
- [ ] Selección de *QGraphicsPolygonItem* con *mousePressEvent*
- [ ] Matrices **responsivas** a figuras
- [ ] Traducir aplicación a Inglés
- [ ] Corregir crash en mallado de figuras superpuestas
- [ ] Agregar **Info Popups** en todas las pestañas

## Cuestiones a considerar
- [ ] Interpolación bicúbica para mallado cuadrángular
- [ ] Botón de Coloreado de plot, después de generar mallado
- [ ] Usar la opción de *Save* para crear y guardar datos. Remover *New*

## :warning: Formato de commits :warning:
Si es de importancia se creará un *Issue* por cada elemento de la lista. 
Para atender un cada *Issue* **será necesario usar el siguiente formato en el commit resuelva el problema**:

```bash
git commit -m "Closes #[Numero de Issue]"
```
#### Por ejemplo:
Si ya se corrijó un *Issue* número 2, se necesita hacer referencia al *Issue* arreglado:
```bash
git commit -m "Se arregló el bug. Closes #2 "
```

**Así tener seguimiento de qué hemos arreglado y qué no.** 🦖

**Comment by montesp** [comment]
🍑

**Comment by wolfieito** [comment]
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣴⣶⣿⣿⣷⣶⣄⣀⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⣾⣿⣿⡿⢿⣿⣿⣿⣿⣿⣿⣿⣷⣦⡀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⣿⡟⠁⣰⣿⣿⣿⡿⠿⠻⠿⣿⣿⣿⣿⣧⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⣾⣿⣿⠏⠀⣴⣿⣿⣿⠉⠀⠀⠀⠀⠀⠈⢻⣿⣿⣇⠀⠀⠀
⠀⠀⠀⠀⢀⣠⣼⣿⣿⡏⠀⢠⣿⣿⣿⠇⠀⠀⠀⠀⠀⠀⠀⠈⣿⣿⣿⡀⠀⠀
⠀⠀⠀⣰⣿⣿⣿⣿⣿⡇⠀⢸⣿⣿⣿⡀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⡇⠀⠀
⠀⠀⢰⣿⣿⡿⣿⣿⣿⡇⠀⠘⣿⣿⣿⣧⠀⠀⠀⠀⠀⠀⢀⣸⣿⣿⣿⠁⠀⠀
⠀⠀⣿⣿⣿⠁⣿⣿⣿⡇⠀⠀⠻⣿⣿⣿⣷⣶⣶⣶⣶⣶⣿⣿⣿⣿⠃⠀⠀⠀
⠀⢰⣿⣿⡇⠀⣿⣿⣿⠀⠀⠀⠀⠈⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⠟⠁⠀⠀⠀⠀
⠀⢸⣿⣿⡇⠀⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠉⠛⠛⠛⠉⢉⣿⣿⠀⠀⠀⠀⠀⠀
⠀⢸⣿⣿⣇⠀⣿⣿⣿⠀⠀⠀⠀⠀⢀⣤⣤⣤⡀⠀⠀⢸⣿⣿⣿⣷⣦⠀⠀⠀
⠀⠀⢻⣿⣿⣶⣿⣿⣿⠀⠀⠀⠀⠀⠈⠻⣿⣿⣿⣦⡀⠀⠉⠉⠻⣿⣿⡇⠀⠀
⠀⠀⠀⠛⠿⣿⣿⣿⣿⣷⣤⡀⠀⠀⠀⠀⠈⠹⣿⣿⣇⣀⠀⣠⣾⣿⣿⡇⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠹⣿⣿⣿⣿⣦⣤⣤⣤⣤⣾⣿⣿⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠻⢿⣿⣿⣿⣿⣿⣿⠿⠋⠉⠛⠋⠉⠉⠁⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠉⠉⠉⠁
