### ISSUE TITLE
Conditions y Conditions PDE to do list

### ISSUE THREAD

**Issue by montesp** [montesp/UICmv#36]
# Todo list conditions pestañas
### Conditions
combo box de type of conditions:
- [ ] Todos los dominios van a tener el valor de thermal insolation por defecto
- [ ] Thermal insolation, agregar valor 0 por defecto, ocultar los elementos del toolbox
- [ ] Temperature, solo seleccionar el valor temperature del toolbox, guardar el valor de el input T
- [ ] Heat flux, mostrar la ventana cuando se selecciona en el combo
- [ ] General inward heat flux , va a mostrar el input q0
- [ ] Convective heat flux , va a mostar el input h y text
- [ ] Seleccionar todos los lados con el all boundarys 
- [ ] Guardar todos los datos con all boundarys
- [ ] Revisar Initial values (junta)
