### ISSUE TITLE
(Pre/Pos)procesado TODO list

### ISSUE THREAD

**Issue by VCAngel** [montesp/UICmv#54]
Aquí están los siguientes TODOs para el pre/pos procesado.
## Preprocesado:
- [ ] Botones de *Done* en todas las pestañas

## Posprocesado:
- [ ] Agregar slider/input para **DOF**
- [ ] Deshabilitar sección de posprocesado si el modo es *Stationary*
- [ ] Quitar mallado cuadrangular
- [ ] Pestaña/Sección de Posprocesado
